(defun my/c-mode-common-hook()
  (setq c-default-style "linux")
  (define-key c-mode-base-map (kbd "C-c C-c") 'align)
  (which-func-mode t)
  (helm-gtags-mode 1)
  (subword-mode 1)
  (display-line-numbers-mode 1)
  ;; (yas-minor-mode 1)
  )
(add-hook 'c-mode-common-hook 'my/c-mode-common-hook)

(setq auto-mode-alist (append '(("\\.h\\'" . c++-mode))
                              '(("\\.hpp\\'" . c++-mode))
                              '(("\\.cc\\'" . c++-mode))
                              '(("\\.cpp\\'" . c++-mode))
                              auto-mode-alist))
